name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux builds
          - arch: armv7
            musl_toolchain: arm-linux-musleabihf-cross
            goarch: arm
          - arch: aarch64
            musl_toolchain: aarch64-linux-musl-cross
            goarch: arm64
          - arch: x86_64
            musl_toolchain: x86_64-linux-musl-cross
            goarch: amd64
          - arch: i686
            musl_toolchain: i686-linux-musl-cross
            goarch: 386
          - arch: mips64
            musl_toolchain: mips64-linux-musl-cross
            goarch: mips64
          - arch: riscv64
            musl_toolchain: riscv64-linux-musl-cross
            goarch: riscv64
          - arch: mipsel
            musl_toolchain: mipsel-linux-musln32sf-cross
            goarch: mipsle
          # Windows build (cross-compiled on Ubuntu)
          - arch: windows-amd64
            goarch: amd64

    name: Build ${{ matrix.arch }} on ubuntu-latest
    env:
      LIBPCAP_VERSION: "1.10.5"
      PROJECT_NAME: "nyn"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/source

      # ========= Linux-specific steps =========
      - name: Setup Linux variables
        if: matrix.musl_toolchain
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MUSL_TOOLCHAIN=${{ matrix.musl_toolchain }}" >> $GITHUB_ENV
          echo "WORKSPACE=${{ github.workspace }}/build" >> $GITHUB_ENV
          echo "BINARY_NAME=$PROJECT_NAME-$VERSION-linux-${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Install Linux dependencies
        if: matrix.musl_toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar xz-utils make gcc

      - name: Setup musl toolchain
        if: matrix.musl_toolchain
        run: |
          mkdir -p $WORKSPACE
          cd $WORKSPACE
          curl -LO "https://musl.cc/$MUSL_TOOLCHAIN.tgz"
          tar -xzf "$MUSL_TOOLCHAIN.tgz"

      - name: Build libpcap (Linux)
        if: matrix.musl_toolchain
        run: |
          cd $WORKSPACE
          curl -LO "https://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.xz"
          tar -xf "libpcap-$LIBPCAP_VERSION.tar.xz"
          cd libpcap-$LIBPCAP_VERSION
          TRIPLET=${MUSL_TOOLCHAIN%-cross}
          CC="$WORKSPACE/$MUSL_TOOLCHAIN/bin/${TRIPLET}-gcc"
          ./configure --host=$TRIPLET --with-pcap=linux --prefix="$WORKSPACE/libpcap-install" CC="$CC"
          make -j$(nproc)
          make install

      - name: Build Linux binary
        if: matrix.musl_toolchain
        run: |
          cd ${{ github.workspace }}/source
          TRIPLET=${MUSL_TOOLCHAIN%-cross}
          CC="$WORKSPACE/$MUSL_TOOLCHAIN/bin/${TRIPLET}-gcc"
          
          if [[ "${{ matrix.arch }}" == "mipsel" ]]; then
            GOMIPS=softfloat
            EXTRA_CFLAGS="-msoft-float"
            EXTRA_LDFLAGS="-msoft-float"
          fi

          CGO_ENABLED=1 GOOS=linux GOARCH=${{ matrix.goarch }} GOARM=${GOARM:-} \
            CC="$CC" \
            CGO_CFLAGS="-I$WORKSPACE/libpcap-install/include $EXTRA_CFLAGS" \
            CGO_LDFLAGS="-L$WORKSPACE/libpcap-install/lib -lpcap $EXTRA_LDFLAGS" \
            go build -ldflags "-s -w" -o "$WORKSPACE/$BINARY_NAME" ./cmd/nyn/

      - name: Upload Linux artifact
        if: matrix.musl_toolchain
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ env.WORKSPACE }}/${{ env.BINARY_NAME }}

      # ========= Windows build steps (cross compile on Ubuntu) =========
      - name: Setup Windows variables
        if: matrix.musl_toolchain == null
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          BINARY_NAME="$PROJECT_NAME-$VERSION-windows-${{ matrix.goarch }}.exe"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV

      - name: Build Windows binary
        if: matrix.musl_toolchain == null
        run: |
          cd ${{ github.workspace }}/source
          GOOS=windows GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w" -o "$BINARY_NAME" ./cmd/nyn/

      - name: Upload Windows artifact
        if: matrix.musl_toolchain == null
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ github.workspace }}/source/${{ env.BINARY_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: "nyn-*"
          merge-multiple: true

      - name: Verify artifacts
        run: |
          echo "=== Downloaded files ==="
          mkdir -p artifacts
          ls -lah artifacts/
          echo "========================"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/nyn-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
